server:
  port: 8888
neo4j:
  url: bolt://127.0.0.1:7687
  username: neo4j
  password: 123456
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false #开发时关闭缓存,不然没法看到实时页面
    prefix: classpath:/templates/ # 默认路径
    suffix: .html # 后缀

#  datasource:
#      url: jdbc:mysql://localhost:3306/db_neo4j?useSSL=false&serverTimezone=UTC
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#      type: com.alibaba.druid.pool.DruidDataSource
#
#mybatis:
#  typeAliasesPackage: com.mn.springboot.model
#  mapperLocations: classpath*:/mappers/*.xml
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql